services:
  fruit_detector:
    labels:
      - deploy.user=${USER}
    image: lcas.lincoln.ac.uk/lcas/ros-docker-images:jammy-cuda11.8-humble-2
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
      target: final
    networks:
      - developer

    cap_add:
      - NET_ADMIN

    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - HOST_USER=${USER:-anonymous}
      - HOST_HOSTNAME=${HOSTNAME:-unknown}

    runtime: nvidia  # Enable NVIDIA runtime for GPU access

    command: "bash -c 'sudo ifconfig lo multicast; sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev lo; sleep infinity'"

    ports:
      - "${HOST_PORT:-5801}:5801"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../:/home/ros/fruit_detector_ws/src/aoc_fruit_detector:rw
      - /media:/media:rw

networks:
  developer:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.container_iface_prefix: "eth"
